### ISSUE TITLE
use modpacktools

### ISSUE THREAD

**Issue by LordMZTE** [ACGaming/Hardcore-Nightmare-IV#1]
Currently, there seems to be no way to build this, so why not use [modpacktools](https://github.com/Anvilcraft/modpacktools) to do that?

**Comment by ACGaming** [comment]
![](https://www.madmonq.gg/wp-content/uploads/2021/04/WeSmart.png)

**Comment by LordMZTE** [comment]
[The new rust rewrite of MPT](https://tilera.xyz/git/LordMZTE/legacympt-rs) is now mature enough to be used here. Should I open a PR switching the project to MPT?
